#!/bin/sh

LoggedInUser=`ls -l /dev/console | awk '/ / { print $3 }'`
LoggedInUserHome="/Users/$LoggedInUser"

configureDefaultDock() {

echo "Logged in user is $LoggedInUser"
echo "Logged in user's home $LoggedInUserHome"

if [ -e /usr/local/bin/dockutil ];
then
   dockutilVersion=`/usr/local/bin/dockutil --version --version`; echo "dockutil version: $dockutilVersion"

dockutil --remove all --no-restart "$LoggedInUserHome"

dockutil --add '/Applications/Safari.app' --no-restart  --position 1 "$LoggedInUserHome"
dockutil --add '/Applications/Google Chrome.app' --no-restart --position 2 "$LoggedInUserHome"
dockutil --add '/Applications/Firefox.app' --no-restart --position 3 "$LoggedInUserHome"
dockutil --add '/Applications/Slack.app' --no-restart --position 4 "$LoggedInUserHome"
dockutil --add '/Applications/Microsoft Teams.app' --no-restart --position 5 "$LoggedInUserHome"
dockutil --add '/Applications/Microsoft Outlook.app' --no-restart --position 6 "$LoggedInUserHome"
dockutil --add '/Applications/Microsoft Word.app' --no-restart --position 7 "$LoggedInUserHome"
dockutil --add '/Applications/Microsoft Excel.app' --no-restart --position 8 "$LoggedInUserHome"
dockutil --add '/Applications/Microsoft PowerPoint.app' --no-restart --position 9 "$LoggedInUserHome"
dockutil --add '/Applications/Microsoft OneNote.app' --no-restart --position 10 "$LoggedInUserHome"
dockutil --add '/Applications/CMU Self Service.app' --no-restart --position 11 "$LoggedInUserHome"
dockutil --add '/Applications/Representative Console - helpdesk.remotesupport.cmich.edu.app' --no-restart --position 12 "$LoggedInUserHome"

touch $LoggedInUserHome/Library/Preferences/com.company.docksetup.plist

else
   echo "dockutil not installed, skipping initial dock setup..."
fi

}

configureDefaultDock
killall -KILL Dock

exit 0
