#!/bin/bash

# Create temporary directory for installer
mkdir /tmp/downloads
cd /tmp/downloads


# Get current available version of VLC Player from site
CurrentVLC=$(curl "http://get.videolan.org/vlc/last/macosx/" | grep .dmg | grep -v webplugin | grep -v md5 | grep -v sha1 | grep -v sha256 | awk '{print $2}' | awk -F ">" '{print $2}' | tr -d "</a")

# Remove current VLC Player (if any)
rm -rf /Applications/VLC.app

# Download current version from site
curl -L -o vlc.dmg http://get.videolan.org/vlc/last/macosx/$CurrentVLC

# Install
hdiutil mount -nobrowse vlc.dmg -mountpoint /Volumes/vlc
rsync -vaz /Volumes/vlc/VLC.app/ /Applications/VLC.app
hdiutil unmount "/Volumes/vlc"

# Cleanup
rm vlc.dmg
rm -rf /tmp/downloads
